URL="https://www.saucedemo.com/"
PATH="data\invalid_valid_login.xls"
LOGIN_BUTTON_ID="login-button"
ERROR_MESSAGE_XPATH="//h3[@data-test='error']"
ERROR_MESSAGE_USERNAME_TEXT="Epic sadface: Username is required"
USERNAME_XPATH="//input[@data-test='username']"
ERROR_MESSAGE_PASSWORD_TEXT="Epic sadface: Password is required"
PASSWORD_XPATH="//input[@data-test='password']"
ERROR_MESSAGE_LOCKED_TEXT ="Epic sadface: Sorry, this user has been locked out."
PRODUCT_LIST_XPATH = "//div[@class='inventory_item']"
SORT_BUTTON_CLASS="product_sort_container"
LOW_TO_HIGH_XPATH="//option[text()='Price (low to high)']"
PRODUCT_PRICE_XPATH="(//div[@class='inventory_item_price'])[3]"
USERNAME_ID="user-name"
PASSWORD_ID="password"
CONTINUE_BUTTON_ID="continue"
FINISH_BUTTON_ID="finish"
ORDER_MESSAGE_CLASS="complete-header"
ORDER_MESSAGE="Thank you for your order!"
FIRSTNAME_TEXT_ID="first-name"
LASTNAME_TEXT_ID="last-name"
POSTALCODE_TEXT_ID="postal-code"
FIRST_PRODUCT_ID="item_4_title_link"
ADD_TO_CART_BUTTON_ID="add-to-cart-sauce-labs-backpack"
CHECKOUT_BUTTON_ID="checkout"
SHOPPING_CART_XPATH="//div[@class='shopping_cart_container']"
FIRSTNAME_TEXT="elif"
LASTNAME_TEXT="isci"
POSTALCODE_TEXT="34000"
VALID_USERNAME="standard_user"
VALID_LOCKED_USERNAME="locked_out_user"
VALID_PASSWORD="secret_sauce"
PRODUCT_PRICE="$15.99"